In [20]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [21]:
from sklearn.datasets import make_classification

X,y=make_classification(n_samples=1000,n_features=3,n_classes=2,n_redundant=1,random_state=10)


In [22]:
X

array([[-0.81775363,  2.86013496,  2.37273791],
       [-0.87108613,  1.66202688, -0.72758967],
       [-0.60387769,  0.94861229, -0.98298974],
       ...,
       [ 1.42310376, -2.20445861,  2.38951619],
       [-0.6458251 ,  0.96668899, -1.16368219],
       [-0.73511361,  2.61680025,  2.2403958 ]])

In [23]:
y

array([1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)


In [25]:
X_train

array([[ 7.62511917e-04,  2.33329769e-01,  5.52578615e-01],
       [-5.23154944e-01,  9.32199117e-01, -5.92076251e-01],
       [ 1.00362054e+00, -1.41982039e+00,  2.00214947e+00],
       ...,
       [-6.63684778e-01,  1.01135453e+00, -1.15370580e+00],
       [-6.37549685e-01,  2.39288912e+00,  2.23312043e+00],
       [ 1.73631371e-01, -1.21812441e-01,  6.37471626e-01]])

In [26]:
from sklearn.neighbors import KNeighborsClassifier

model=KNeighborsClassifier(n_neighbors=6,algorithm='auto')
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=6)

In [27]:
y_pred=model.predict(X_test)


In [28]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred=y_pred,y_true=y_test))

0.8933333333333333


##Trying to predict best value of K

In [44]:
from sklearn.model_selection import GridSearchCV
param_grid=[{'n_neighbors':[1,2,3,4,5,6,7,8,9,10]}]

grid=GridSearchCV(KNeighborsClassifier(),param_grid=param_grid,verbose=3)


In [45]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END .....................n_neighbors=1;, score=0.807 total time=   0.0s
[CV 2/5] END .....................n_neighbors=1;, score=0.764 total time=   0.0s
[CV 3/5] END .....................n_neighbors=1;, score=0.836 total time=   0.0s
[CV 4/5] END .....................n_neighbors=1;, score=0.864 total time=   0.0s
[CV 5/5] END .....................n_neighbors=1;, score=0.843 total time=   0.0s
[CV 1/5] END .....................n_neighbors=2;, score=0.836 total time=   0.0s
[CV 2/5] END .....................n_neighbors=2;, score=0.771 total time=   0.0s
[CV 3/5] END .....................n_neighbors=2;, score=0.843 total time=   0.0s
[CV 4/5] END .....................n_neighbors=2;, score=0.886 total time=   0.0s
[CV 5/5] END .....................n_neighbors=2;, score=0.864 total time=   0.0s
[CV 1/5] END .....................n_neighbors=3;, score=0.843 total time=   0.0s
[CV 2/5] END .....................n_neighbors=3;

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid=[{'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}],
             verbose=3)

In [46]:
grid.best_params_

{'n_neighbors': 6}

In [48]:
model=KNeighborsClassifier(n_neighbors=6,algorithm='auto')
model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=6)

In [49]:
y_pred=model.predict(X_test)


In [50]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred=y_pred,y_true=y_test))

0.8933333333333333
